name: Run tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.4
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - uses: actions/checkout@v1
        name: Checkout code

      - uses: actions/cache@v1
        name: Cache Go modules
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Bootstrap
        run: |
          go get github.com/golang/mock/mockgen
          export PATH=$PATH:$HOME/go/bin
          go generate ./...

      - name: Run tests
        run: |
          go test ./...
          go vet ./...
