name: Run tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.4
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - uses: actions/checkout@v1
        name: Checkout code

      - name: Bootstrap
        run: |
          go get ./...
          export PATH="$PATH":${GOPATH:-${{ github.workspace}}/bin}
          go generate ./...

      - name: Run tests
        run: go test ./...
